#!/bin/bash
# execd        Init script for running the execd client daemon
#
# Author:       Duane Griffin <d.griffin@psenterprise.com>
#               David Lutterkort <dlutter@redhat.com>
#
# chkconfig: - 98 02
#
# description: Enables periodic system configuration checks through execd.
# processname: execd
# config: /etc/sysconfig/execd

PATH=/usr/bin:/sbin:/bin:/usr/sbin
export PATH

if [ -f /etc/sysconfig/gridengine ]; then
    source /etc/sysconfig/gridengine
else
    echo "No sysconfig file found! Exiting..."
    exit 1
fi

ARCH=$($SGE_ROOT/util/arch)
SGE_BINDIR=$SGE_ROOT/bin/$ARCH
EXECD_PORT=$(awk '/sge_execd/ { print $2 }' /etc/services | sed 's/\/tcp$//g')

RETVAL=0

if [ -f $SGE_ROOT/$SGE_CELL/common/settings.sh ]; then
	source $SGE_ROOT/$SGE_CELL/common/settings.sh
else
	echo "Configuration file missing!  Exiting..."
fi

# Source function library.
. /etc/rc.d/init.d/functions

start() {
    action $"Starting execd: " $SGE_ROOT/$SGE_CELL/common/sgeexecd start
    RETVAL=$?
    return $RETVAL
}

stop() {
    action $"Stopping execd: " $SGE_ROOT/$SGE_CELL/common/sgeexecd stop
    RETVAL=$?
    return $RETVAL
}

restart() {
    stop
    start
}

rh_status() {
    $SGE_BINDIR/qping -info $(hostname) $EXECD_PORT execd 1 > /dev/null 2>&1
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        echo "execd is running..."
    else
        echo "execd is stopped."
    fi
    return $RETVAL
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    status)
        rh_status
    ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 1
esac

exit $RETVAL
